FROM oven/bun:1

WORKDIR /app

COPY package*.json ./
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json
COPY ./apps/backend ./apps/backend

# COPY . .

RUN bun install
RUN bun run db:generate

EXPOSE 8080

CMD ["bun", "run", "start:backend"]
