FROM oven/bun:1

WORKDIR /app

COPY package*.json ./
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json
COPY ./apps/web ./apps/web

# COPY . .

RUN bun install
RUN bun run db:generate
RUN bun run build

EXPOSE 3001

CMD ["bun", "run", "start:frontend"]